language: node_js
node_js:
  - '0.10'
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meanjs' ]; then cd .. && eval "mv $currentfolder generator-meanjs" && cd generator-meanjs; fi

