language: node_js
node_js:
  - 0.12
  - 4
  - 5
os: 
  - linux
  - centos
  - windows
  - macosx
matrix:
  allow_failures:
    - node_js: 5
sudo: false
cache:
  apt: true
  directories:
  - node_modules/
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meanjs' ]; then cd .. && eval "mv $currentfolder generator-meanjs" && cd generator-meanjs; fi

